apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Override namespace
namespace: harbor-day2-op

# Common annotations
commonAnnotations:
  goharbor.io/operator-version: "v1.0.0"
  goharbor.io/template: "Kustomization"

# All the referred deployment manifests
resources:
  - ../config/default

# Image Used
images:
  - name: controller
    newName: goharbor/harbor-day2-operator
    newTag: dev