# permissions for end users to view pullsecretbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pullsecretbinding-viewer-role
rules:
- apiGroups:
  - goharbor.goharbor.io
  resources:
  - pullsecretbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - goharbor.goharbor.io
  resources:
  - pullsecretbindings/status
  verbs:
  - get
