# permissions for end users to edit pullsecretbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pullsecretbinding-editor-role
rules:
- apiGroups:
  - goharbor.goharbor.io
  resources:
  - pullsecretbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - goharbor.goharbor.io
  resources:
  - pullsecretbindings/status
  verbs:
  - get
