apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: kube-system
type: Opaque
data:
  username: YWRtaW4=
  password: SGFyYm9yMTIzNDU=
---
apiVersion: goharbor.goharbor.io/v1alpha1
kind: HarborServerConfiguration
metadata:
  name: harborserverconfiguration-sample
spec:
  serverURL: goharbor.io
  accessCredential:
    namespace: kube-system
    accessSecretRef: mysecret
  version: 2.1.0
  default: false
